typography_spectrum: 0.78631
color:
  brandColors:
    - '#313131'
    - '#fafafa'
    - '#b5b5b5'
    - '#4d4d4d'
    - '#797979'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 0
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0
analytics:
  google: null
  facebook: null
  twitter: null
name: Robert August
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Robert August
purpose: []
