name: Robert August
favicon: null
layout_spectrum: 0
typography_spectrum: 1
title: Robert August
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f3f3f3'
    - '#cfceca'
    - '#a09f9b'
    - '#898884'
    - '#757470'
  brandStrength: 0
  lightness: 0
  saturation: 0
  rhythmicContrast: 1
purpose: []
