name: Robert August
favicon: null
layout_spectrum: 0.83556
typography_spectrum: 0.75625
title: Robert August
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#010101'
    - '#c2c2c2'
    - '#8d8d8d'
    - '#393939'
  brandStrength: 0
  lightness: 1
  saturation: 0
  rhythmicContrast: 0
purpose: []
