name: Robert August
favicon: null
layout_spectrum: 1
typography_spectrum: 1
title: Robert August
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#060606'
    - '#eae4e5'
    - '#d6ac9f'
    - '#53240d'
    - '#ec490b'
  brandStrength: 1
  lightness: 0
  saturation: 0
  rhythmicContrast: 1
purpose: []
