name: Robert August
favicon: null
layout_spectrum: 0
typography_spectrum: 0.14819461572915316
title: Robert August
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f3f3f3'
    - '#cfceca'
    - '#a09f9b'
    - '#898884'
    - '#757470'
  brandStrength: 0.9900663075968623
  lightness: 0.75
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
